baseURL: https://georgeprof.github.io/
theme: minimal
title: georgeprof
# disqusShortname: username
# googleAnalytics: ""
languageCode: en-us
disableHugoGeneratorInject: true
uglyurls: false
canonifyurls: false
publishdir: georgeprof.github.io
permalinks:
  page: /:slug/
  post: /post/:slug/
menu:
  icon:
  - name: envelope-o
    url: mailto:me@example.com
    weight: 1
  # - name: github
  #   url: https://github.com/georgeprof/
  #   weight: 2
  # - name: twitter
  #   url: https://twitter.com/georgeprof/
  #   weight: 3
  # - name: linkedin
  #   url: https://www.linkedin.com/in/georgeprof/
  #   weight: 4
  # - name: stack-overflow
  #   url: https://www.stackoverflow.com/username/
  #   weight: 5
  main:
  - name: Home
    url: /
    weight: 1
  - name: Posts
    url: /post/
    weight: 2
params:
  accent: black
  author: georgeprof
  backgroundColor: white
  # description: Чтоб мотор завелся - надо включить зажигание!
  font: Ubuntu
  githubUsername: '#'
  highlight: true
  highlightLanguages:
  - go
  - haskell
  - kotlin
  - scala
  - swift
  highlightStyle: solarized-dark
  showBorder: true
